tailscale/tailscale-synology

- README.md
The amd64 package worked great.
> Add DS918+ to compatibility list

- README.md
Thanks a ton for your work on this. Just wanted to add my device to the compatibility list. Cheers
Signed-off-by: Tyler Rivera <tyler.rivera@gmail.com>
> Adds ds216play compatibility to readme

- README.md
- src/INFO.sh
Thanks for putting this together. It works great!
> Add compatability for DS212j (armv5)

- README.md
> Update README.md - DS1815+ Works Great

- README.md
Verified that my new DS920+ works as well, so let's add it. Maybe it's time to just do a generic table instead?
> Add DS920+

- README.md
Works for me. Thanks for this!
> Add DS220+ to compatibility list

- README.md
Tested it today, works great so far.
> Add DS413j to the compatibility list in the readme

- README.md
I think I've put the right thing in the platform column I wasn't really sure exactly what that column means so I took a bit of a guess
> Add DS2015xs to compatibility list

- README.md
Just used this to install tailscale on my DS115j successfully. So have added it to the list of compatible models
> Add DS115j to compatibility list

- README.md
Just installed the arm64 release on my ds220j and it worked without issue.
> Add ds220j to compatibility list

- README.md
Works perfectly with the ARM64 build.
>  Updating README.md for DSM218play

- README.md
Can confirm that DS418J is working with the arm64 build
> Updating README.md for DS418J

- README.md
I have been using this package for a while on a DS718+ without any issues. Thanks for your work!
> Add DS718+ to the compatibility list

- Makefile
- build-package.sh
- src/INFO.sh
- src/config
Lets a user login using the Synology GUI.
> CGI script for Tailscale App on Synology

- Makefile
- build-package.sh
- src/INFO.sh
- src/scripts/start-stop-status
> Update list of platforms for synology.

- build-package.sh
- src/resource
- src/scripts/start-stop-status
> Change the logpolicy directory and stop logging "No such process" errors

- README.md
> Improve README.md install instructions

- Makefile
- src/scripts/start-stop-status
> remove logs from start-stop-status

- Makefile
- src/scripts/start-stop-status
> fix status reporting

- README.md
See https://github.com/tailscale/tailscale/issues/2829 for reference.
> readme: add note about building on macOS

- Makefile
- build-package.sh
> Update to 1.14.3

- Makefile
> update to v1.14.4

- Makefile
> update to 1.16.2

- Makefile
Signed-off-by: Denton Gentry <dgentry@tailscale.com>
> Update to 1.18.0

- Makefile
Signed-off-by: Denton Gentry <dgentry@tailscale.com>
> Makefile: Update to OSS 1.20.0.

- .github/workflows/main.yml
> .github/workflows: add permissions to write packages

- Makefile
> Makefile: update to 1.20.1

- .github/workflows/main.yml
> .github/workflows: fix the perms for real

- .github/workflows/main.yml
> .github/workflows: give permissions to write contents

- .github/workflows/main.yml
> .github/workflows: use new go build tool

- build.go
> build: only use `.priv` files for DSM7+

- build.go
- go.mod
Signed-off-by: David Anderson <dave@natulte.net>
> go.mod: update tailscale.com, fix up build logic
